
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test1@example.com','$3a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',1,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test2@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test3@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test4@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test5@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test6@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test7@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test8@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
insert into idm.users (user_name,password,admin,user_data,reset_guid,reset_required)values('test9@example.com','$2a$10$dh/WkFg7f0EBnaP8723xXeU1mX2nUtx9fmi1few3VJwkNOjvuwD6K',0,'{"firstname":"User"}',uuid_in(md5(random()::text || now()::text)::cstring),1) on conflict do nothing;
